spring.datasource.url=jdbc:mariadb://192.168.142.129:3306/jobbridge
spring.datasource.username=ykk
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.connection-timeout=5000

spring.sql.init.mode=never
