spring.datasource.url=jdbc:mariadb://${DB_HOST:192.168.126.129}:${DB_PORT:3306}/${DB_NAME:jobbridge}
spring.datasource.username=${DB_USERNAME:ykk}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.connection-timeout=5000

spring.sql.init.mode=never
