server.port = 8080

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://192.168.142.129:3306/jobbridge?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=ykk
spring.datasource.password=1234
spring.datasource.hikari.connection-timeout=5000

mybatis.type-aliases-package=org.ykk.jobbridge.dto
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.sql.init.mode=never
spring.devtools.restart.enabled=false
spring.web.resources.static-locations=file:./src/main/resources/static/,classpath:/static/
spring.web.resources.cache.period=0

kakao.rest-api-key=${KAKAO_REST_API_KEY:}
kakao.enabled=false
#
#openai.api-key=${OPENAI_API_KEY:}
openai.enabled=false
openai.model=gemini-3.5-flash-lite
openai.chat-completions-url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions

kead.api.url=https://apis.data.go.kr/B552583/job2/job_list2
kead.api.service-key=${KEAD_API_SERVICE_KEY:}
kead.api.enabled=true
kead.api.page-size=100
kead.api.max-pages=20
