ALTER TABLE job_posting
    MODIFY COLUMN employment_type ENUM(
        'ANY', 'FULL_TIME', 'REGULAR_EMPLOYEE', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE'
    ) NOT NULL;

ALTER TABLE job_seeker_profile
    MODIFY COLUMN employment_type ENUM(
        'ANY', 'FULL_TIME', 'REGULAR_EMPLOYEE', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE'
    ) NOT NULL DEFAULT 'ANY';

ALTER TABLE job_application
    MODIFY COLUMN employment_type ENUM(
        'ANY', 'FULL_TIME', 'REGULAR_EMPLOYEE', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE'
    ) NULL DEFAULT NULL;
