-- 기존 V6는 이미 적용된 마이그레이션이므로 수정하지 않고, 여기서 9개 표준 코드로 통일한다.
ALTER TABLE job_seeker_profile MODIFY COLUMN employment_type VARCHAR(50) NULL;
ALTER TABLE job_posting MODIFY COLUMN employment_type VARCHAR(50) NULL;
ALTER TABLE job_application MODIFY COLUMN employment_type VARCHAR(50) NULL;

UPDATE job_seeker_profile
SET employment_type = CASE UPPER(TRIM(COALESCE(employment_type, '')))
    WHEN 'ANY' THEN 'ANY' WHEN '무관' THEN 'ANY'
    WHEN 'FULL_TIME' THEN 'FULL_TIME' WHEN '정규직' THEN 'FULL_TIME'
    WHEN 'CONTRACT' THEN 'CONTRACT' WHEN '계약직' THEN 'CONTRACT'
    WHEN 'PERMANENT_CONTRACT' THEN 'PERMANENT_CONTRACT' WHEN '무기계약직' THEN 'PERMANENT_CONTRACT'
    WHEN 'CONVERSION_TYPE' THEN 'CONVERSION_TYPE' WHEN 'FULL_TIME_CONVERSION' THEN 'CONVERSION_TYPE'
    WHEN '정규직 전환형' THEN 'CONVERSION_TYPE'
    WHEN 'PART_TIME' THEN 'PART_TIME' WHEN '시간제·파트타임' THEN 'PART_TIME'
    WHEN '시간제' THEN 'PART_TIME' WHEN '파트타임' THEN 'PART_TIME'
    WHEN '알바' THEN 'PART_TIME' WHEN '아르바이트' THEN 'PART_TIME'
    WHEN 'INTERN' THEN 'INTERN' WHEN 'INTERNSHIP' THEN 'INTERN'
    WHEN '인턴' THEN 'INTERN' WHEN '인턴십' THEN 'INTERN'
    WHEN 'DISPATCH' THEN 'DISPATCH' WHEN '파견직' THEN 'DISPATCH'
    WHEN 'FREELANCE' THEN 'FREELANCE' WHEN 'FREELANCER' THEN 'FREELANCE'
    WHEN '프리랜서' THEN 'FREELANCE'
    ELSE 'ANY' END;

UPDATE job_posting
SET employment_type = CASE UPPER(TRIM(COALESCE(employment_type, '')))
    WHEN 'ANY' THEN 'ANY' WHEN '무관' THEN 'ANY'
    WHEN 'FULL_TIME' THEN 'FULL_TIME' WHEN '정규직' THEN 'FULL_TIME'
    WHEN 'CONTRACT' THEN 'CONTRACT' WHEN '계약직' THEN 'CONTRACT'
    WHEN 'PERMANENT_CONTRACT' THEN 'PERMANENT_CONTRACT' WHEN '무기계약직' THEN 'PERMANENT_CONTRACT'
    WHEN 'CONVERSION_TYPE' THEN 'CONVERSION_TYPE' WHEN 'FULL_TIME_CONVERSION' THEN 'CONVERSION_TYPE'
    WHEN '정규직 전환형' THEN 'CONVERSION_TYPE'
    WHEN 'PART_TIME' THEN 'PART_TIME' WHEN '시간제·파트타임' THEN 'PART_TIME'
    WHEN '시간제' THEN 'PART_TIME' WHEN '파트타임' THEN 'PART_TIME'
    WHEN '알바' THEN 'PART_TIME' WHEN '아르바이트' THEN 'PART_TIME'
    WHEN 'INTERN' THEN 'INTERN' WHEN 'INTERNSHIP' THEN 'INTERN'
    WHEN '인턴' THEN 'INTERN' WHEN '인턴십' THEN 'INTERN'
    WHEN 'DISPATCH' THEN 'DISPATCH' WHEN '파견직' THEN 'DISPATCH'
    WHEN 'FREELANCE' THEN 'FREELANCE' WHEN 'FREELANCER' THEN 'FREELANCE'
    WHEN '프리랜서' THEN 'FREELANCE'
    ELSE 'ANY' END;

UPDATE job_application
SET employment_type = CASE UPPER(TRIM(COALESCE(employment_type, '')))
    WHEN 'ANY' THEN 'ANY' WHEN '무관' THEN 'ANY'
    WHEN 'FULL_TIME' THEN 'FULL_TIME' WHEN '정규직' THEN 'FULL_TIME'
    WHEN 'CONTRACT' THEN 'CONTRACT' WHEN '계약직' THEN 'CONTRACT'
    WHEN 'PERMANENT_CONTRACT' THEN 'PERMANENT_CONTRACT' WHEN '무기계약직' THEN 'PERMANENT_CONTRACT'
    WHEN 'CONVERSION_TYPE' THEN 'CONVERSION_TYPE' WHEN 'FULL_TIME_CONVERSION' THEN 'CONVERSION_TYPE'
    WHEN '정규직 전환형' THEN 'CONVERSION_TYPE'
    WHEN 'PART_TIME' THEN 'PART_TIME' WHEN '시간제·파트타임' THEN 'PART_TIME'
    WHEN '시간제' THEN 'PART_TIME' WHEN '파트타임' THEN 'PART_TIME'
    WHEN '알바' THEN 'PART_TIME' WHEN '아르바이트' THEN 'PART_TIME'
    WHEN 'INTERN' THEN 'INTERN' WHEN 'INTERNSHIP' THEN 'INTERN'
    WHEN '인턴' THEN 'INTERN' WHEN '인턴십' THEN 'INTERN'
    WHEN 'DISPATCH' THEN 'DISPATCH' WHEN '파견직' THEN 'DISPATCH'
    WHEN 'FREELANCE' THEN 'FREELANCE' WHEN 'FREELANCER' THEN 'FREELANCE'
    WHEN '프리랜서' THEN 'FREELANCE'
    ELSE 'ANY' END;

ALTER TABLE job_seeker_profile
    MODIFY COLUMN employment_type ENUM('ANY', 'FULL_TIME', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE') NOT NULL DEFAULT 'ANY';
ALTER TABLE job_posting
    MODIFY COLUMN employment_type ENUM('ANY', 'FULL_TIME', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE') NOT NULL;
ALTER TABLE job_application
    MODIFY COLUMN employment_type ENUM('ANY', 'FULL_TIME', 'CONTRACT', 'PERMANENT_CONTRACT',
        'CONVERSION_TYPE', 'PART_TIME', 'INTERN', 'DISPATCH', 'FREELANCE') NULL;
