ALTER TABLE job_seeker_profile
    ADD COLUMN IF NOT EXISTS rest_area_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS elevator_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE job_posting
    ADD COLUMN IF NOT EXISTS rest_area_available BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS elevator_available BOOLEAN NOT NULL DEFAULT FALSE;
